### ISSUE TITLE
Simplify API

### ISSUE THREAD

**Issue by igorkamyshev** [neurosnap/gen-readlines#12]
Hello! Great lib, thanks.

What do you thunk about simplification API?

Like this:
```js
function* readFile() {
  for (let line of readlines('./file.txt')) {
    console.log(line.toString());
  }
}
```

**Comment by neurosnap** [comment]
Thanks!

I think originally I wrote it like this but I decided to make the library a
little leaner and got rid of it. Happy to accept PRs for the feature as
long as we don't break backwards compatibility.

**Comment by igorkamyshev** [comment]
Ok, I will implement that.

What about `readlines.fromFile()` ? Or maybe you have a better name for this function?

**Comment by neurosnap** [comment]
That sounds good to me!

**Comment by igorkamyshev** [comment]
Or may be use simplified version just if first argument is string?
