### ISSUE TITLE
Empty lines are being swallowed

### ISSUE THREAD

**Issue by silkentrance** [neurosnap/gen-readlines#2]
Given the input file

```
# Comment



# TODO:something
```

readlines will return

```
# Comment
# TODO:something
```

All empty line are being swallowed.

**Comment by neurosnap** [comment]
Hmm yes I think I assumed -- wrongly -- that a line with just a newline character should be ignored.

I'm making the change now.  Thanks for the input!

**Comment by neurosnap** [comment]
Published 0.1.0 to npm: https://www.npmjs.com/package/gen-readlines

**Comment by silkentrance** [comment]
Great thanks!
