### ISSUE TITLE
The latest fix for windos line endings does not work

### ISSUE THREAD

**Issue by silkentrance** [neurosnap/gen-readlines#6]
I am sorry, but the latest fix for windos line endings CR+LF does not work as expected.

While I was working on the code to further optimize it and finally used istanbul to check on overall coverage, it turned out that the detection of the CR+LF is not working at all when reading in buffers larger than a single byte.

For now, I have extended upon the available test cases so that it will detect such an issue and am now working on fixing this ASAP.

**Comment by silkentrance** [comment]
Heck, it even swallows part of the existing contents. The existing test cases are weak and I will have to extend upon that as well...

**Comment by silkentrance** [comment]
Moving let readChunk = new Buffer(bufferSize) to outside of the loop caused numerous side effects.
Will move it back into the loop although this might reduce overall performance.

Moved it back and it now works better while causing existing tests to fail, but this is a good sign...

**Comment by silkentrance** [comment]
See the follow up PR for more information.

**Comment by silkentrance** [comment]
Fleshed out existing bug, still I get \r as part of the yielded lines...

**Comment by neurosnap** [comment]
Lemme know what I can do to help, it'll be easier for me to understand the problem when I can see some test failures.

**Comment by silkentrance** [comment]
Found the issue. When copying the remainder, it always copied the whole buffer even though bytesRead could be less than the original buffer size with which the buffer was initialized.
